version: "3.7"

services:
  # MongoDB
  cadmus-vela-mongo:
    image: mongo
    container_name: cadmus-vela-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-vela-network

 # PostgreSQL
  cadmus-vela-pgsql:
    image: postgres
    container_name: cadmus-vela-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-vela-network

  # Cadmus VeLA API
  cadmus-vela-api:
    image: vedph2020/cadmus-vela-api:3.0.0
    container_name: cadmus-vela-api
    ports:
      # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
      - 5080:80
    depends_on:
      - cadmus-vela-mongo
      - cadmus-vela-pgsql
    environment:
      # for Windows use : as separator, for non Windows use __
      # (see https://github.com/aspnet/Configuration/issues/469)
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-vela-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-vela-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-vela-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-vela-network

  # Cadmus VeLA App
  cadmus-app:
    image: vedph2020/cadmus-vela-app:3.0.0
    container_name: cadmus-vela-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-vela-api
    networks:
      - cadmus-vela-network

networks:
  cadmus-vela-network:
    driver: bridge
